### ISSUE TITLE
BROKER_ID parameter not recognized?

### ISSUE THREAD

**Issue by bluepuma77** [gten/docker-kafka-cluster#1]
I can't run the second node, seems the BROKER_ID is not correctly recognized.

On the command line I set it to 1, within Docker it's suddenly 0.

```
#docker run \
>   --name=kafka2 \
>   -p 9092:9092 \
>   -e KAFKA_HOST=server2.server.de \
>   -e KAFKA_PORT=9092 \
>   -e ZOOKEEPER_CONNECT=server1.server.de:2181,server2.server.de:2181 \
>   -e BROKER_ID=1 \
>   -d jeygeethan/kafka-cluster
9f7137bbf5269c1810308d0f28bfdf33a83673e250b2947877daf5f4e05d486c

# docker logs -f kafka2
advertised host: server2.server.de
advertised port: 9092
zookeeper connect: server1.server.de.de:2181,server2.server.de.de:2181
[2017-04-05 21:53:55,272] INFO KafkaConfig values:
	advertised.host.name = server2.server.de
	...
	broker.id = 0
	...
 (kafka.server.KafkaConfig)
[2017-04-05 21:53:55,309] INFO starting (kafka.server.KafkaServer)
[2017-04-05 21:53:55,311] INFO Connecting to zookeeper on server1.server.de:2181,server2.server.de:2181 (kafka.server.KafkaServer)
[2017-04-05 21:53:55,318] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-04-05 21:53:55,321] INFO Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT (org.apache.zookeeper.ZooKeeper)
[2017-04-05 21:53:55,321] INFO Client environment:host.name=9f7137bbf526 (org.apache.zookeeper.ZooKeeper)
[2017-04-05 21:53:55,321] INFO Client environment:java.version=1.8.0_102 (org.apache.zookeeper.ZooKeeper)
[2017-04-05 21:53:55,321] INFO Client environment:java.vendor=Oracle Corporation (org.apache.zookeeper.ZooKeeper)
[2017-04-05 21:53:55,321] INFO Client environment:java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre (org.apache.zookeeper.ZooKeeper)
...
[2017-04-05 21:53:55,686] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
[2017-04-05 21:53:55,694] INFO Result of znode creation is: NODEEXISTS (kafka.utils.ZKCheckedEphemeral)
[2017-04-05 21:53:55,695] FATAL [Kafka Server 0], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.RuntimeException: A broker is already registered on the path /brokers/ids/0. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.
	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:295)
	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:281)
	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:64)
	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:45)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:231)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:37)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2017-04-05 21:53:55,696] INFO [Kafka Server 0], shutting down (kafka.server.KafkaServer)
[2017-04-05 21:53:55,697] INFO [Socket Server on Broker 0], Shutting down (kafka.network.SocketServer)
[2017-04-05 21:53:55,704] INFO [Socket Server on Broker 0], Shutdown completed (kafka.network.SocketServer)
```

**Comment by UnsignedInt8** [comment]
```
# Set the broker id
if [ ! -z "$KAFKA_ID" ]; then
    echo "broker id: $KAFKA_ID"
    sed -r -i "s/(broker.id)=(.*)/\1=$KAFKA_ID/g" $KAFKA_HOME/config/server.properties
fi
```

I guess it should be 'KAFKA_ID'

**Comment by cutejaneii** [comment]
Yes, it should be "KAFKA_ID", and it works.

For example, it should be 
docker run -d -p 9092:9092 -e KAFKA_HOST=192.168.0.1 -e KAFKA_PORT=9092 \
-e ZOOKEEPER_CONNECT=192.168.0.1:2181,192.168.0.2:2181,192.168.0.3:2181 -e KAFKA_ID=0 --name kafka-1 jeygeethan/kafka-cluster

use "-e KAFKA_ID" when docker run.

**Comment by abhishekjalan87** [comment]
Guys any idea, how we can set env for log.dirs=/tmp/kafka-logs to log.dirs=/var/log/kafka-logs

can we define this while running the docker?
